name: clear-redis

on:
  workflow_dispatch:

jobs:
  clear-redis:
    runs-on: ubuntu-latest

    steps:
      - name: clear redis from mobility server
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ./key.pem
          chmod 600 ./key.pem
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          ssh -i ./key.pem ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} <<EOF
          docker restart redis-server_second
          

          EOF
